"""Add statistics models: match_statistics, player_match_statistics, club_season_statistics,
   player_season_statistics

Revision ID: 26261d486b2e
Revises: aac509491515
Create Date: 2025-11-11 20:31:52.749310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26261d486b2e'
down_revision: Union[str, None] = 'aac509491515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_season_statistics',
    sa.Column('club_stats_id', sa.UUID(), nullable=False, comment='Unique record ID'),
    sa.Column('club_id', sa.UUID(), nullable=False, comment='Club reference (CASCADE on deletion, UNIQUE)'),
    sa.Column('matches_played', sa.Integer(), server_default='0', nullable=False, comment='Total matches played'),
    sa.Column('wins', sa.Integer(), server_default='0', nullable=False, comment='Wins'),
    sa.Column('draws', sa.Integer(), server_default='0', nullable=False, comment='Draws'),
    sa.Column('losses', sa.Integer(), server_default='0', nullable=False, comment='Losses'),
    sa.Column('goals_scored', sa.Integer(), server_default='0', nullable=False, comment='Total goals scored'),
    sa.Column('goals_conceded', sa.Integer(), server_default='0', nullable=False, comment='Total goals conceded'),
    sa.Column('total_clean_sheets', sa.Integer(), server_default='0', nullable=False, comment='Clean sheets'),
    sa.Column('avg_goals_per_match', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg goals per match'),
    sa.Column('avg_possession_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg possession %'),
    sa.Column('avg_total_shots', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg shots per match'),
    sa.Column('avg_shots_on_target', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg shots on target'),
    sa.Column('avg_xg_per_match', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg xG per match'),
    sa.Column('avg_goals_conceded_per_match', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg goals conceded'),
    sa.Column('avg_total_passes', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg passes per match'),
    sa.Column('pass_completion_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Overall pass accuracy %'),
    sa.Column('avg_final_third_passes', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg final third passes'),
    sa.Column('avg_crosses', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg crosses per match'),
    sa.Column('avg_dribbles', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg dribbles per match'),
    sa.Column('avg_successful_dribbles', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg successful dribbles'),
    sa.Column('avg_tackles', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg tackles per match'),
    sa.Column('tackle_success_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Overall tackle success %'),
    sa.Column('avg_interceptions', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg interceptions'),
    sa.Column('interception_success_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Overall interception success %'),
    sa.Column('avg_ball_recoveries', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg ball recoveries'),
    sa.Column('avg_saves_per_match', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg goalkeeper saves'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last calculation time'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_stats_id'),
    sa.UniqueConstraint('club_id')
    )
    op.create_index('idx_club_season_statistics_club_id', 'club_season_statistics', ['club_id'], unique=True)
    op.create_table('match_statistics',
    sa.Column('statistics_id', sa.UUID(), nullable=False, comment='Unique statistics record ID'),
    sa.Column('match_id', sa.UUID(), nullable=False, comment='Match reference (CASCADE on deletion)'),
    sa.Column('team_type', sa.String(length=20), nullable=False, comment="'our_team' or 'opponent_team'"),
    sa.Column('possession_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Ball possession %'),
    sa.Column('expected_goals', sa.Numeric(precision=8, scale=6), nullable=True, comment='xG (StatsBomb uses up to 8 decimal places)'),
    sa.Column('total_shots', sa.Integer(), nullable=True, comment='Total shots'),
    sa.Column('shots_on_target', sa.Integer(), nullable=True, comment='Shots on target'),
    sa.Column('shots_off_target', sa.Integer(), nullable=True, comment='Shots off target'),
    sa.Column('goalkeeper_saves', sa.Integer(), nullable=True, comment='Saves by goalkeeper'),
    sa.Column('total_passes', sa.Integer(), nullable=True, comment='Total passes'),
    sa.Column('passes_completed', sa.Integer(), nullable=True, comment='Completed passes'),
    sa.Column('pass_completion_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Pass accuracy %'),
    sa.Column('passes_in_final_third', sa.Integer(), nullable=True, comment='Passes in final third'),
    sa.Column('long_passes', sa.Integer(), nullable=True, comment='Long passes'),
    sa.Column('crosses', sa.Integer(), nullable=True, comment='Crosses'),
    sa.Column('total_dribbles', sa.Integer(), nullable=True, comment='Dribbles attempted'),
    sa.Column('successful_dribbles', sa.Integer(), nullable=True, comment='Successful dribbles'),
    sa.Column('total_tackles', sa.Integer(), nullable=True, comment='Tackles attempted'),
    sa.Column('tackle_success_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Tackle success %'),
    sa.Column('interceptions', sa.Integer(), nullable=True, comment='Interceptions'),
    sa.Column('ball_recoveries', sa.Integer(), nullable=True, comment='Ball recoveries'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.CheckConstraint("team_type IN ('our_team', 'opponent_team')", name='ck_match_statistics_team_type'),
    sa.CheckConstraint('match_id IS NOT NULL AND team_type IS NOT NULL', name='uq_match_statistics_match_team'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statistics_id')
    )
    op.create_index('idx_match_statistics_match_id', 'match_statistics', ['match_id'], unique=False)
    op.create_table('player_match_statistics',
    sa.Column('player_match_stats_id', sa.UUID(), nullable=False, comment='Unique record ID'),
    sa.Column('player_id', sa.UUID(), nullable=False, comment='Player reference (CASCADE on deletion)'),
    sa.Column('match_id', sa.UUID(), nullable=False, comment='Match reference (CASCADE on deletion)'),
    sa.Column('goals', sa.Integer(), server_default='0', nullable=False, comment='Goals scored'),
    sa.Column('assists', sa.Integer(), server_default='0', nullable=False, comment='Assists'),
    sa.Column('expected_goals', sa.Numeric(precision=8, scale=6), nullable=True, comment='Player xG'),
    sa.Column('shots', sa.Integer(), nullable=True, comment='Total shots'),
    sa.Column('shots_on_target', sa.Integer(), nullable=True, comment='Shots on target'),
    sa.Column('total_dribbles', sa.Integer(), nullable=True, comment='Dribbles attempted'),
    sa.Column('successful_dribbles', sa.Integer(), nullable=True, comment='Successful dribbles'),
    sa.Column('total_passes', sa.Integer(), nullable=True, comment='Total passes'),
    sa.Column('completed_passes', sa.Integer(), nullable=True, comment='Completed passes'),
    sa.Column('short_passes', sa.Integer(), nullable=True, comment='Short passes'),
    sa.Column('long_passes', sa.Integer(), nullable=True, comment='Long passes'),
    sa.Column('final_third_passes', sa.Integer(), nullable=True, comment='Passes in final third'),
    sa.Column('crosses', sa.Integer(), nullable=True, comment='Crosses'),
    sa.Column('tackles', sa.Integer(), nullable=True, comment='Tackles'),
    sa.Column('tackle_success_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Tackle success %'),
    sa.Column('interceptions', sa.Integer(), nullable=True, comment='Interceptions'),
    sa.Column('interception_success_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Interception success %'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_match_stats_id')
    )
    op.create_index('idx_player_match_statistics_match_id', 'player_match_statistics', ['match_id'], unique=False)
    op.create_index('idx_player_match_statistics_player_id', 'player_match_statistics', ['player_id'], unique=False)
    op.create_table('player_season_statistics',
    sa.Column('player_stats_id', sa.UUID(), nullable=False, comment='Unique record ID'),
    sa.Column('player_id', sa.UUID(), nullable=False, comment='Player reference (CASCADE on deletion, UNIQUE)'),
    sa.Column('matches_played', sa.Integer(), server_default='0', nullable=False, comment='Matches played'),
    sa.Column('goals', sa.Integer(), server_default='0', nullable=False, comment='Total goals'),
    sa.Column('assists', sa.Integer(), server_default='0', nullable=False, comment='Total assists'),
    sa.Column('expected_goals', sa.Numeric(precision=8, scale=6), nullable=True, comment='Total xG'),
    sa.Column('shots_per_game', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg shots per game'),
    sa.Column('shots_on_target_per_game', sa.Numeric(precision=5, scale=2), nullable=True, comment='Avg shots on target'),
    sa.Column('total_passes', sa.Integer(), nullable=True, comment='Total passes'),
    sa.Column('passes_completed', sa.Integer(), nullable=True, comment='Completed passes'),
    sa.Column('total_dribbles', sa.Integer(), nullable=True, comment='Total dribbles'),
    sa.Column('successful_dribbles', sa.Integer(), nullable=True, comment='Successful dribbles'),
    sa.Column('tackles', sa.Integer(), nullable=True, comment='Total tackles'),
    sa.Column('tackle_success_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Tackle success %'),
    sa.Column('interceptions', sa.Integer(), nullable=True, comment='Total interceptions'),
    sa.Column('interception_success_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Interception success %'),
    sa.Column('attacking_rating', sa.Integer(), nullable=True, comment='Attacking attribute (0-100)'),
    sa.Column('technique_rating', sa.Integer(), nullable=True, comment='Technique attribute (0-100)'),
    sa.Column('tactical_rating', sa.Integer(), nullable=True, comment='Tactical attribute (0-100)'),
    sa.Column('defending_rating', sa.Integer(), nullable=True, comment='Defending attribute (0-100)'),
    sa.Column('creativity_rating', sa.Integer(), nullable=True, comment='Creativity attribute (0-100)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last calculation time'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_stats_id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index('idx_player_season_statistics_player_id', 'player_season_statistics', ['player_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_player_season_statistics_player_id', table_name='player_season_statistics')
    op.drop_table('player_season_statistics')
    op.drop_index('idx_player_match_statistics_player_id', table_name='player_match_statistics')
    op.drop_index('idx_player_match_statistics_match_id', table_name='player_match_statistics')
    op.drop_table('player_match_statistics')
    op.drop_index('idx_match_statistics_match_id', table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index('idx_club_season_statistics_club_id', table_name='club_season_statistics')
    op.drop_table('club_season_statistics')
    # ### end Alembic commands ###
