"""Add training models: training_plans and training_exercises

Revision ID: 2c84469970f0
Revises: 26261d486b2e
Create Date: 2025-11-11 20:48:13.396875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c84469970f0'
down_revision: Union[str, None] = '26261d486b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False, comment='Unique plan ID'),
    sa.Column('player_id', sa.UUID(), nullable=False, comment='Assigned player (CASCADE on deletion)'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Coach who created plan (SET NULL on deletion)'),
    sa.Column('plan_name', sa.String(length=255), nullable=False, comment='Plan name'),
    sa.Column('duration', sa.String(length=50), nullable=True, comment="Duration (e.g., '2 weeks')"),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment="Status: 'pending', 'in_progress', 'completed'"),
    sa.Column('coach_notes', sa.Text(), nullable=True, comment='Instructions from coach'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Plan creation time'),
    sa.ForeignKeyConstraint(['created_by'], ['coaches.coach_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index('idx_training_plans_player_id', 'training_plans', ['player_id'], unique=False)
    op.create_index('idx_training_plans_status', 'training_plans', ['status'], unique=False)
    op.create_table('training_exercises',
    sa.Column('exercise_id', sa.UUID(), nullable=False, comment='Unique exercise ID'),
    sa.Column('plan_id', sa.UUID(), nullable=False, comment='Parent plan (CASCADE on deletion)'),
    sa.Column('exercise_name', sa.String(length=255), nullable=False, comment='Exercise name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Exercise description/instructions'),
    sa.Column('sets', sa.String(length=20), nullable=True, comment='Number of sets (string for flexibility)'),
    sa.Column('reps', sa.String(length=20), nullable=True, comment='Number of reps (string for flexibility)'),
    sa.Column('duration_minutes', sa.String(length=20), nullable=True, comment='Duration in minutes (string for flexibility)'),
    sa.Column('exercise_order', sa.Integer(), nullable=False, comment='Display order within the plan'),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=False, comment='Has player completed this exercise?'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When player marked it complete'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Exercise creation time'),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_index('idx_training_exercises_plan_id', 'training_exercises', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_training_exercises_plan_id', table_name='training_exercises')
    op.drop_table('training_exercises')
    op.drop_index('idx_training_plans_status', table_name='training_plans')
    op.drop_index('idx_training_plans_player_id', table_name='training_plans')
    op.drop_table('training_plans')
    # ### end Alembic commands ###
