"""Change player user_id to SET NULL; add age_group enum

Revision ID: 4a423284273a
Revises: cec718a67a72
Create Date: 2025-11-10 19:28:35.831446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a423284273a'
down_revision: Union[str, None] = 'cec718a67a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create the enum type first
    agegroup_enum = sa.Enum('U6', 'U8', 'U10', 'U12', 'U14', 'U16', 'U18', 'U21', 'SENIOR', name='agegroup')
    agegroup_enum.create(op.get_bind(), checkfirst=True)

    # 2. Now alter the column to use the enum
    op.alter_column('clubs', 'age_group',
               existing_type=sa.VARCHAR(length=20),
               type_=agegroup_enum,
               comment='Team age group (U6, U8, U10, U12, U14, U16, U18, U21, or Senior)',
               existing_comment="Team age group (e.g., 'U16', 'U18')",
               existing_nullable=True,
               postgresql_using='age_group::text::agegroup')  # Convert existing values

    # 3. Update player user_id comment
    op.alter_column('players', 'user_id',
               existing_type=sa.UUID(),
               comment='Reference to user account (NULL before signup or after user deletion)',
               existing_comment='Reference to user account (NULL before signup)',
               existing_nullable=True)

    # 4. Change foreign key to SET NULL on delete
    op.drop_constraint('players_user_id_fkey', 'players', type_='foreignkey')
    op.create_foreign_key('players_user_id_fkey', 'players', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Restore foreign key to CASCADE
    op.drop_constraint('players_user_id_fkey', 'players', type_='foreignkey')
    op.create_foreign_key('players_user_id_fkey', 'players', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # 2. Restore player user_id comment
    op.alter_column('players', 'user_id',
               existing_type=sa.UUID(),
               comment='Reference to user account (NULL before signup)',
               existing_comment='Reference to user account (NULL before signup or after user deletion)',
               existing_nullable=True)

    # 3. Alter column back to VARCHAR
    op.alter_column('clubs', 'age_group',
               existing_type=sa.Enum('U6', 'U8', 'U10', 'U12', 'U14', 'U16', 'U18', 'U21', 'SENIOR', name='agegroup'),
               type_=sa.VARCHAR(length=20),
               comment="Team age group (e.g., 'U16', 'U18')",
               existing_comment='Team age group (U6, U8, U10, U12, U14, U16, U18, U21, or Senior)',
               existing_nullable=True)

    # 4. Drop the enum type
    sa.Enum('U6', 'U8', 'U10', 'U12', 'U14', 'U16', 'U18', 'U21', 'SENIOR', name='agegroup').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
