"""Add match-related models: opponent_clubs, matches, opponent_players, goals, events

Revision ID: 59ce4e824ea4
Revises: 4a423284273a
Create Date: 2025-11-11 20:11:20.398269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59ce4e824ea4'
down_revision: Union[str, None] = '4a423284273a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first (order matters for foreign key constraints)
    op.drop_index('ix_match_statistics_match_id', table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index('ix_training_exercises_plan_id', table_name='training_exercises')
    op.drop_table('training_exercises')
    op.drop_index('ix_training_plans_created_by', table_name='training_plans')
    op.drop_index('ix_training_plans_player_id', table_name='training_plans')
    op.drop_index('ix_training_plans_status', table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index('ix_player_match_statistics_match_id', table_name='player_match_statistics')
    op.drop_index('ix_player_match_statistics_player_id', table_name='player_match_statistics')
    op.drop_table('player_match_statistics')
    op.drop_index('ix_club_season_statistics_club_id', table_name='club_season_statistics')
    op.drop_table('club_season_statistics')
    op.drop_index('ix_player_season_statistics_player_id', table_name='player_season_statistics')
    op.drop_table('player_season_statistics')
    op.alter_column('events', 'event_id',
               existing_type=sa.UUID(),
               comment='Unique event identifier',
               existing_nullable=False)
    op.alter_column('events', 'match_id',
               existing_type=sa.UUID(),
               comment='Match reference (CASCADE on deletion)',
               existing_nullable=False)
    op.alter_column('events', 'statsbomb_player_id',
               existing_type=sa.INTEGER(),
               comment='StatsBomb player ID',
               existing_nullable=True)
    op.alter_column('events', 'statsbomb_team_id',
               existing_type=sa.INTEGER(),
               comment='StatsBomb team ID',
               existing_nullable=True)
    op.alter_column('events', 'player_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Player name from event',
               existing_nullable=True)
    op.alter_column('events', 'team_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Team name from event',
               existing_nullable=True)
    op.alter_column('events', 'event_type_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Event type (Pass, Shot, etc.)',
               existing_nullable=True)
    op.alter_column('events', 'position_name',
               existing_type=sa.VARCHAR(length=50),
               comment='Player position',
               existing_nullable=True)
    op.alter_column('events', 'minute',
               existing_type=sa.INTEGER(),
               comment='Match minute',
               existing_nullable=True)
    op.alter_column('events', 'second',
               existing_type=sa.INTEGER(),
               comment='Second within minute',
               existing_nullable=True)
    op.alter_column('events', 'period',
               existing_type=sa.INTEGER(),
               comment='Match period',
               existing_nullable=True)
    op.alter_column('events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full event JSON data (JSONB in PostgreSQL, JSON in SQLite)',
               existing_nullable=True)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index('idx_events_event_data', table_name='events', postgresql_using='gin')
    op.drop_index('ix_events_event_type_name', table_name='events')
    op.drop_index('ix_events_match_id', table_name='events')
    op.drop_index('ix_events_statsbomb_player_id', table_name='events')
    op.create_index('idx_events_event_type_name', 'events', ['event_type_name'], unique=False)
    op.create_index('idx_events_match_id', 'events', ['match_id'], unique=False)
    op.create_index('idx_events_statsbomb_player_id', 'events', ['statsbomb_player_id'], unique=False)
    # Create GIN index for JSONB event_data (PostgreSQL specific)
    op.create_index('idx_events_event_data', 'events', ['event_data'], unique=False, postgresql_using='gin')
    op.alter_column('goals', 'goal_id',
               existing_type=sa.UUID(),
               comment='Unique goal identifier',
               existing_nullable=False)
    op.alter_column('goals', 'match_id',
               existing_type=sa.UUID(),
               comment='Match reference (CASCADE on deletion)',
               existing_nullable=False)
    op.alter_column('goals', 'team_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Team that scored',
               existing_nullable=False)
    op.alter_column('goals', 'scorer_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Player who scored',
               existing_nullable=False)
    op.alter_column('goals', 'assist_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Player who assisted (nullable)',
               existing_nullable=True)
    op.alter_column('goals', 'minute',
               existing_type=sa.INTEGER(),
               comment='Match minute',
               existing_nullable=False)
    op.alter_column('goals', 'second',
               existing_type=sa.INTEGER(),
               comment='Second within minute',
               existing_nullable=True)
    op.alter_column('goals', 'period',
               existing_type=sa.INTEGER(),
               comment='Match period (1, 2, etc.)',
               existing_nullable=False)
    op.alter_column('goals', 'goal_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of goal (Open Play, Penalty, etc.)',
               existing_nullable=True)
    op.alter_column('goals', 'body_part',
               existing_type=sa.VARCHAR(length=50),
               comment='Body part used (Right Foot, Header, etc.)',
               existing_nullable=True)
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index('ix_goals_match_id', table_name='goals')
    op.create_index('idx_goals_match_id', 'goals', ['match_id'], unique=False)
    op.alter_column('matches', 'match_id',
               existing_type=sa.UUID(),
               comment='Unique match identifier',
               existing_nullable=False)
    op.alter_column('matches', 'club_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Our club (SET NULL on club deletion)')
    op.alter_column('matches', 'opponent_club_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Opponent club (CASCADE on deletion)')
    op.alter_column('matches', 'opponent_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Opponent name (denormalized for easier queries)',
               existing_nullable=False)
    op.alter_column('matches', 'match_date',
               existing_type=sa.DATE(),
               comment='Match date',
               existing_nullable=False)
    op.alter_column('matches', 'match_time',
               existing_type=postgresql.TIME(),
               comment='Match kickoff time',
               existing_nullable=True)
    op.alter_column('matches', 'is_home_match',
               existing_type=sa.BOOLEAN(),
               comment='Is this a home match?',
               existing_nullable=False)
    op.alter_column('matches', 'home_score',
               existing_type=sa.INTEGER(),
               comment='Final home team score (NULL until match complete)',
               existing_nullable=True)
    op.alter_column('matches', 'away_score',
               existing_type=sa.INTEGER(),
               comment='Final away team score (NULL until match complete)',
               existing_nullable=True)
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('matches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.drop_index('ix_matches_club_id', table_name='matches')
    op.drop_index('ix_matches_match_date', table_name='matches')
    op.create_index('idx_matches_club_id', 'matches', ['club_id'], unique=False)
    op.create_index('idx_matches_match_date', 'matches', ['match_date'], unique=False)
    op.drop_constraint('matches_opponent_club_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_club_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'clubs', ['club_id'], ['club_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'matches', 'opponent_clubs', ['opponent_club_id'], ['opponent_club_id'], ondelete='CASCADE')
    op.alter_column('opponent_clubs', 'opponent_club_id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the opponent club',
               existing_nullable=False)
    op.alter_column('opponent_clubs', 'opponent_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the opponent team',
               existing_nullable=False)
    op.alter_column('opponent_clubs', 'statsbomb_team_id',
               existing_type=sa.INTEGER(),
               comment="StatsBomb's unique team identifier",
               existing_nullable=True)
    op.alter_column('opponent_clubs', 'logo_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               comment="URL to the opponent's logo image",
               existing_nullable=True)
    op.alter_column('opponent_clubs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index('ix_opponent_clubs_statsbomb_team_id', table_name='opponent_clubs')
    op.alter_column('opponent_players', 'opponent_player_id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the opponent player',
               existing_nullable=False)
    op.alter_column('opponent_players', 'opponent_club_id',
               existing_type=sa.UUID(),
               comment='Opponent club (CASCADE on deletion)',
               existing_nullable=False)
    op.alter_column('opponent_players', 'player_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Player name from event data',
               existing_nullable=False)
    op.alter_column('opponent_players', 'statsbomb_player_id',
               existing_type=sa.INTEGER(),
               comment='StatsBomb player ID',
               existing_nullable=True)
    op.alter_column('opponent_players', 'jersey_number',
               existing_type=sa.INTEGER(),
               comment="Player's jersey number",
               existing_nullable=True)
    op.alter_column('opponent_players', 'position',
               existing_type=sa.VARCHAR(length=50),
               comment='Player position',
               existing_nullable=True)
    op.alter_column('opponent_players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index('ix_opponent_players_opponent_club_id', table_name='opponent_players')
    op.drop_index('ix_opponent_players_statsbomb_player_id', table_name='opponent_players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_opponent_players_statsbomb_player_id', 'opponent_players', ['statsbomb_player_id'], unique=False)
    op.create_index('ix_opponent_players_opponent_club_id', 'opponent_players', ['opponent_club_id'], unique=False)
    op.alter_column('opponent_players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('opponent_players', 'position',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Player position',
               existing_nullable=True)
    op.alter_column('opponent_players', 'jersey_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Player's jersey number",
               existing_nullable=True)
    op.alter_column('opponent_players', 'statsbomb_player_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='StatsBomb player ID',
               existing_nullable=True)
    op.alter_column('opponent_players', 'player_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Player name from event data',
               existing_nullable=False)
    op.alter_column('opponent_players', 'opponent_club_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Opponent club (CASCADE on deletion)',
               existing_nullable=False)
    op.alter_column('opponent_players', 'opponent_player_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the opponent player',
               existing_nullable=False)
    op.create_index('ix_opponent_clubs_statsbomb_team_id', 'opponent_clubs', ['statsbomb_team_id'], unique=False)
    op.alter_column('opponent_clubs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('opponent_clubs', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               comment=None,
               existing_comment="URL to the opponent's logo image",
               existing_nullable=True)
    op.alter_column('opponent_clubs', 'statsbomb_team_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="StatsBomb's unique team identifier",
               existing_nullable=True)
    op.alter_column('opponent_clubs', 'opponent_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the opponent team',
               existing_nullable=False)
    op.alter_column('opponent_clubs', 'opponent_club_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the opponent club',
               existing_nullable=False)
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_club_id_fkey', 'matches', 'clubs', ['club_id'], ['club_id'], ondelete='CASCADE')
    op.create_foreign_key('matches_opponent_club_id_fkey', 'matches', 'opponent_clubs', ['opponent_club_id'], ['opponent_club_id'], ondelete='SET NULL')
    op.drop_index('idx_matches_match_date', table_name='matches')
    op.drop_index('idx_matches_club_id', table_name='matches')
    op.create_index('ix_matches_match_date', 'matches', ['match_date'], unique=False)
    op.create_index('ix_matches_club_id', 'matches', ['club_id'], unique=False)
    op.alter_column('matches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('matches', 'away_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Final away team score (NULL until match complete)',
               existing_nullable=True)
    op.alter_column('matches', 'home_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Final home team score (NULL until match complete)',
               existing_nullable=True)
    op.alter_column('matches', 'is_home_match',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Is this a home match?',
               existing_nullable=False)
    op.alter_column('matches', 'match_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Match kickoff time',
               existing_nullable=True)
    op.alter_column('matches', 'match_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Match date',
               existing_nullable=False)
    op.alter_column('matches', 'opponent_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Opponent name (denormalized for easier queries)',
               existing_nullable=False)
    op.alter_column('matches', 'opponent_club_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='Opponent club (CASCADE on deletion)')
    op.alter_column('matches', 'club_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='Our club (SET NULL on club deletion)')
    op.alter_column('matches', 'match_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique match identifier',
               existing_nullable=False)
    op.drop_index('idx_goals_match_id', table_name='goals')
    op.create_index('ix_goals_match_id', 'goals', ['match_id'], unique=False)
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('goals', 'body_part',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Body part used (Right Foot, Header, etc.)',
               existing_nullable=True)
    op.alter_column('goals', 'goal_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of goal (Open Play, Penalty, etc.)',
               existing_nullable=True)
    op.alter_column('goals', 'period',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Match period (1, 2, etc.)',
               existing_nullable=False)
    op.alter_column('goals', 'second',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Second within minute',
               existing_nullable=True)
    op.alter_column('goals', 'minute',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Match minute',
               existing_nullable=False)
    op.alter_column('goals', 'assist_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Player who assisted (nullable)',
               existing_nullable=True)
    op.alter_column('goals', 'scorer_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Player who scored',
               existing_nullable=False)
    op.alter_column('goals', 'team_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Team that scored',
               existing_nullable=False)
    op.alter_column('goals', 'match_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Match reference (CASCADE on deletion)',
               existing_nullable=False)
    op.alter_column('goals', 'goal_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique goal identifier',
               existing_nullable=False)
    op.drop_index('idx_events_statsbomb_player_id', table_name='events')
    op.drop_index('idx_events_match_id', table_name='events')
    op.drop_index('idx_events_event_type_name', table_name='events')
    op.create_index('ix_events_statsbomb_player_id', 'events', ['statsbomb_player_id'], unique=False)
    op.create_index('ix_events_match_id', 'events', ['match_id'], unique=False)
    op.create_index('ix_events_event_type_name', 'events', ['event_type_name'], unique=False)
    op.create_index('idx_events_event_data', 'events', ['event_data'], unique=False, postgresql_using='gin')
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full event JSON data (JSONB in PostgreSQL, JSON in SQLite)',
               existing_nullable=True)
    op.alter_column('events', 'period',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Match period',
               existing_nullable=True)
    op.alter_column('events', 'second',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Second within minute',
               existing_nullable=True)
    op.alter_column('events', 'minute',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Match minute',
               existing_nullable=True)
    op.alter_column('events', 'position_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Player position',
               existing_nullable=True)
    op.alter_column('events', 'event_type_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Event type (Pass, Shot, etc.)',
               existing_nullable=True)
    op.alter_column('events', 'team_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Team name from event',
               existing_nullable=True)
    op.alter_column('events', 'player_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Player name from event',
               existing_nullable=True)
    op.alter_column('events', 'statsbomb_team_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='StatsBomb team ID',
               existing_nullable=True)
    op.alter_column('events', 'statsbomb_player_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='StatsBomb player ID',
               existing_nullable=True)
    op.alter_column('events', 'match_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Match reference (CASCADE on deletion)',
               existing_nullable=False)
    op.alter_column('events', 'event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique event identifier',
               existing_nullable=False)
    op.create_table('player_season_statistics',
    sa.Column('player_stats_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('matches_played', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('goals', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('expected_goals', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True),
    sa.Column('shots_per_game', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('shots_on_target_per_game', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_dribbles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_dribbles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackle_success_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interception_success_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('attacking_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technique_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tactical_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('defending_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creativity_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name='player_season_statistics_player_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_stats_id', name='player_season_statistics_pkey'),
    sa.UniqueConstraint('player_id', name='player_season_statistics_player_id_key')
    )
    op.create_index('ix_player_season_statistics_player_id', 'player_season_statistics', ['player_id'], unique=True)
    op.create_table('club_season_statistics',
    sa.Column('club_stats_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('matches_played', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('wins', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('draws', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('losses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('goals_scored', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('goals_conceded', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_clean_sheets', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('avg_goals_per_match', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_goals_conceded_per_match', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_possession_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_xg_per_match', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_total_shots', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_shots_on_target', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_total_passes', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('pass_completion_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_final_third_passes', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_crosses', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_dribbles', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_successful_dribbles', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_tackles', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('tackle_success_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_interceptions', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('interception_success_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_ball_recoveries', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_saves_per_match', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], name='club_season_statistics_club_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_stats_id', name='club_season_statistics_pkey'),
    sa.UniqueConstraint('club_id', name='club_season_statistics_club_id_key')
    )
    op.create_index('ix_club_season_statistics_club_id', 'club_season_statistics', ['club_id'], unique=True)
    op.create_table('player_match_statistics',
    sa.Column('player_match_stats_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goals', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('assists', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('expected_goals', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True),
    sa.Column('shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_on_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_dribbles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_dribbles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('short_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('final_third_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crosses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackle_success_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interception_success_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name='player_match_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name='player_match_statistics_player_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_match_stats_id', name='player_match_statistics_pkey'),
    sa.UniqueConstraint('player_id', 'match_id', name='uq_player_match_statistics_player_match')
    )
    op.create_index('ix_player_match_statistics_player_id', 'player_match_statistics', ['player_id'], unique=False)
    op.create_index('ix_player_match_statistics_match_id', 'player_match_statistics', ['match_id'], unique=False)
    op.create_table('training_exercises',
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exercise_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('exercise_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exercise_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repetitions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.plan_id'], name='training_exercises_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', name='training_exercises_pkey')
    )
    op.create_index('ix_training_exercises_plan_id', 'training_exercises', ['plan_id'], unique=False)
    op.create_table('training_plans',
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('plan_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('plan_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['coaches.coach_id'], name='training_plans_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name='training_plans_player_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', name='training_plans_pkey')
    )
    op.create_index('ix_training_plans_status', 'training_plans', ['status'], unique=False)
    op.create_index('ix_training_plans_player_id', 'training_plans', ['player_id'], unique=False)
    op.create_index('ix_training_plans_created_by', 'training_plans', ['created_by'], unique=False)
    op.create_table('match_statistics',
    sa.Column('statistics_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('possession_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('expected_goals', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True),
    sa.Column('total_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_on_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shots_off_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeper_saves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passes_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pass_completion_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('passes_in_final_third', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crosses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_dribbles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_dribbles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tackles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tackle_success_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_recoveries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name='match_statistics_match_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statistics_id', name='match_statistics_pkey'),
    sa.UniqueConstraint('match_id', 'team_type', name='uq_match_statistics_match_team')
    )
    op.create_index('ix_match_statistics_match_id', 'match_statistics', ['match_id'], unique=False)
    # ### end Alembic commands ###
