"""apply_phase_2_5_schema_changes

Revision ID: 90388be62f06
Revises: a720e6ffcee1
Create Date: 2025-11-16 08:31:14.070481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.base import GUID

# revision identifiers, used by Alembic.
revision: str = '90388be62f06'
down_revision: Union[str, None] = 'a720e6ffcee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_lineups',
    sa.Column('lineup_id', GUID(), nullable=False, comment='Unique lineup entry identifier'),
    sa.Column('match_id', GUID(), nullable=False, comment='Match reference (CASCADE on deletion)'),
    sa.Column('team_type', sa.String(length=20), nullable=False, comment="Team type: 'our_team' or 'opponent_team'"),
    sa.Column('player_id', GUID(), nullable=True, comment='Our player reference (CASCADE on deletion, NULL for opponent)'),
    sa.Column('opponent_player_id', GUID(), nullable=True, comment='Opponent player reference (CASCADE on deletion, NULL for our team)'),
    sa.Column('player_name', sa.String(length=255), nullable=False, comment='Player name (denormalized)'),
    sa.Column('jersey_number', sa.Integer(), nullable=False, comment='Jersey number in this match'),
    sa.Column('position', sa.String(length=50), nullable=False, comment='Player position in this match'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.CheckConstraint("team_type IN ('our_team', 'opponent_team')", name='check_team_type'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_player_id'], ['opponent_players.opponent_player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lineup_id')
    )
    op.create_index('idx_match_lineups_match_id', 'match_lineups', ['match_id'], unique=False)
    op.create_index('idx_match_lineups_opponent_player_id', 'match_lineups', ['opponent_player_id'], unique=False)
    op.create_index('idx_match_lineups_player_id', 'match_lineups', ['player_id'], unique=False)
    op.add_column('club_season_statistics', sa.Column('total_assists', sa.Integer(), server_default='0', nullable=False, comment='Total assists'))
    op.add_column('club_season_statistics', sa.Column('team_form', sa.String(length=5), nullable=True, comment="Last 5 match results (e.g., 'WWDLW')"))
    op.add_column('goals', sa.Column('is_our_goal', sa.Boolean(), nullable=False, comment='True if scored by our team, False if opponent'))
    op.drop_column('goals', 'assist_name')
    op.drop_column('goals', 'body_part')
    op.drop_column('goals', 'team_name')
    op.drop_column('goals', 'period')
    op.drop_column('goals', 'goal_type')
    op.add_column('matches', sa.Column('our_score', sa.Integer(), nullable=True, comment="Our club's final score (NULL until match complete)"))
    op.add_column('matches', sa.Column('opponent_score', sa.Integer(), nullable=True, comment="Opponent's final score (NULL until match complete)"))
    op.add_column('matches', sa.Column('result', sa.String(length=1), nullable=True, comment='Match result from our perspective: W/D/L (NULL until match complete)'))
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'))
    op.drop_column('matches', 'home_score')
    op.drop_column('matches', 'match_time')
    op.drop_column('matches', 'away_score')
    op.drop_column('matches', 'is_home_match')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('is_home_match', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is this a home match?'))
    op.add_column('matches', sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=True, comment='Final away team score (NULL until match complete)'))
    op.add_column('matches', sa.Column('match_time', postgresql.TIME(), autoincrement=False, nullable=True, comment='Match kickoff time'))
    op.add_column('matches', sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=True, comment='Final home team score (NULL until match complete)'))
    op.drop_column('matches', 'updated_at')
    op.drop_column('matches', 'result')
    op.drop_column('matches', 'opponent_score')
    op.drop_column('matches', 'our_score')
    op.add_column('goals', sa.Column('goal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Type of goal (Open Play, Penalty, etc.)'))
    op.add_column('goals', sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False, comment='Match period (1, 2, etc.)'))
    op.add_column('goals', sa.Column('team_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Team that scored'))
    op.add_column('goals', sa.Column('body_part', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Body part used (Right Foot, Header, etc.)'))
    op.add_column('goals', sa.Column('assist_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Player who assisted (nullable)'))
    op.drop_column('goals', 'is_our_goal')
    op.drop_column('club_season_statistics', 'team_form')
    op.drop_column('club_season_statistics', 'total_assists')
    op.drop_index('idx_match_lineups_player_id', table_name='match_lineups')
    op.drop_index('idx_match_lineups_opponent_player_id', table_name='match_lineups')
    op.drop_index('idx_match_lineups_match_id', table_name='match_lineups')
    op.drop_table('match_lineups')
    # ### end Alembic commands ###
