"""standardize timestamp fields across models

Revision ID: a720e6ffcee1
Revises: de0e95c995bd
Create Date: 2025-11-12 22:07:30.609113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a720e6ffcee1'
down_revision: Union[str, None] = 'de0e95c995bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_season_statistics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'))
    op.alter_column('club_season_statistics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was last updated',
               existing_comment='Last calculation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('matches', 'updated_at')
    op.add_column('player_season_statistics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'))
    op.alter_column('player_season_statistics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was last updated',
               existing_comment='Last calculation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('training_exercises', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'))
    op.alter_column('training_exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_comment='Exercise creation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('training_plans', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'))
    op.alter_column('training_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_comment='Plan creation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Plan creation time',
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('training_plans', 'updated_at')
    op.alter_column('training_exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Exercise creation time',
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('training_exercises', 'updated_at')
    op.alter_column('player_season_statistics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last calculation time',
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('player_season_statistics', 'created_at')
    op.add_column('matches', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Timestamp when record was last updated'))
    op.alter_column('club_season_statistics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last calculation time',
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('club_season_statistics', 'created_at')
    # ### end Alembic commands ###
