"""Change club_id to CASCADE and NOT NULL in matches table

Revision ID: aac509491515
Revises: fa912f5abb62
Create Date: 2025-11-11 20:21:27.751640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac509491515'
down_revision: Union[str, None] = 'fa912f5abb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'club_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Our club (CASCADE on deletion)',
               existing_comment='Our club (SET NULL on club deletion)')
    op.drop_constraint('matches_club_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'clubs', ['club_id'], ['club_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_club_id_fkey', 'matches', 'clubs', ['club_id'], ['club_id'], ondelete='SET NULL')
    op.alter_column('matches', 'club_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Our club (SET NULL on club deletion)',
               existing_comment='Our club (CASCADE on deletion)')
    # ### end Alembic commands ###
