"""Initial schema with users, coaches, clubs, and players tables

Revision ID: cec718a67a72
Revises: 
Create Date: 2025-11-08 23:23:22.977908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec718a67a72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (used for login)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password (never store plain text!)'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full name"),
    sa.Column('user_type', sa.String(length=20), nullable=False, comment="Type of user: 'coach' or 'player'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_table('coaches',
    sa.Column('coach_id', sa.UUID(as_uuid=False), nullable=False, comment='Unique coach identifier'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='Reference to user account (one-to-one)'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment="Coach's birth date"),
    sa.Column('gender', sa.String(length=20), nullable=True, comment="Coach's gender"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id')
    )
    op.create_index(op.f('ix_coaches_user_id'), 'coaches', ['user_id'], unique=True)
    op.create_table('clubs',
    sa.Column('club_id', sa.UUID(as_uuid=False), nullable=False, comment='Unique club identifier'),
    sa.Column('coach_id', sa.UUID(as_uuid=False), nullable=False, comment='Owner coach (one-to-one)'),
    sa.Column('club_name', sa.String(length=255), nullable=False, comment='Club/team name'),
    sa.Column('statsbomb_team_id', sa.Integer(), nullable=True, comment='StatsBomb team ID for data matching'),
    sa.Column('country', sa.String(length=100), nullable=True, comment="Club's country"),
    sa.Column('age_group', sa.String(length=20), nullable=True, comment="Team age group (e.g., 'U16', 'U18')"),
    sa.Column('stadium', sa.String(length=255), nullable=True, comment='Home stadium name'),
    sa.Column('logo_url', sa.String(), nullable=True, comment='Club logo image URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id'),
    sa.UniqueConstraint('statsbomb_team_id')
    )
    op.create_index(op.f('ix_clubs_coach_id'), 'clubs', ['coach_id'], unique=True)
    op.create_table('players',
    sa.Column('player_id', sa.UUID(as_uuid=False), nullable=False, comment='Unique player identifier'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True, comment='Reference to user account (NULL before signup)'),
    sa.Column('club_id', sa.UUID(as_uuid=False), nullable=False, comment="Player's club"),
    sa.Column('player_name', sa.String(length=255), nullable=False, comment='Player name (source of truth for display)'),
    sa.Column('statsbomb_player_id', sa.Integer(), nullable=True, comment='StatsBomb player ID from event data'),
    sa.Column('jersey_number', sa.Integer(), nullable=False, comment="Player's jersey/shirt number"),
    sa.Column('position', sa.String(length=50), nullable=False, comment="Player position (e.g., 'Forward', 'Midfielder')"),
    sa.Column('invite_code', sa.String(length=10), nullable=False, comment='Unique signup code (format: XXX-NNNN)'),
    sa.Column('is_linked', sa.Boolean(), nullable=False, comment='Has player completed signup?'),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when player completed signup'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment="Player's birth date (filled on signup)"),
    sa.Column('height', sa.Integer(), nullable=True, comment='Player height in cm (filled on signup)'),
    sa.Column('profile_image_url', sa.String(), nullable=True, comment='Profile photo URL (filled on signup)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_club_id'), 'players', ['club_id'], unique=False)
    op.create_index(op.f('ix_players_invite_code'), 'players', ['invite_code'], unique=True)
    op.create_index(op.f('ix_players_is_linked'), 'players', ['is_linked'], unique=False)
    op.create_index(op.f('ix_players_statsbomb_player_id'), 'players', ['statsbomb_player_id'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_statsbomb_player_id'), table_name='players')
    op.drop_index(op.f('ix_players_is_linked'), table_name='players')
    op.drop_index(op.f('ix_players_invite_code'), table_name='players')
    op.drop_index(op.f('ix_players_club_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_clubs_coach_id'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_coaches_user_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
