"""change logo_url and profile_image_url to text type

Revision ID: de0e95c995bd
Revises: 2c84469970f0
Create Date: 2025-11-12 21:11:09.901361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0e95c995bd'
down_revision: Union[str, None] = '2c84469970f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clubs', 'logo_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_comment='Club logo image URL',
               existing_nullable=True)
    op.alter_column('players', 'profile_image_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_comment='Profile photo URL (filled on signup)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'profile_image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_comment='Profile photo URL (filled on signup)',
               existing_nullable=True)
    op.alter_column('clubs', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_comment='Club logo image URL',
               existing_nullable=True)
    # ### end Alembic commands ###
