"""Make opponent_club_id nullable in matches table

Revision ID: fa912f5abb62
Revises: 59ce4e824ea4
Create Date: 2025-11-11 20:18:14.148860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa912f5abb62'
down_revision: Union[str, None] = '59ce4e824ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_event_data', table_name='events', postgresql_using='gin')
    op.alter_column('matches', 'opponent_club_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Opponent club (CASCADE on deletion, nullable)',
               existing_comment='Opponent club (CASCADE on deletion)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'opponent_club_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Opponent club (CASCADE on deletion)',
               existing_comment='Opponent club (CASCADE on deletion, nullable)')
    op.create_index('idx_events_event_data', 'events', ['event_data'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
